document.write("<table width=\"743\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("  <tr>");
document.write("    <td width=\"262\" height=\"23\" background=\"/images/1.gif\"><table width=\"97%\" border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("      <tr>");
document.write("        <td><table width=\"100%\" border=\"0\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" class=\"zuo\">");
document.write("              <tr>");
document.write("            <td>");
document.write("              <DIV id=jnkc style=\"height: 12; width: 220\"></DIV>");
document.write("              <SCRIPT>setInterval(\"jnkc.innerHTML=new Date().toLocaleString()+' 星期'+'日一二三四五六'.charAt(new Date().getDay());\",1000);");
document.write("        </SCRIPT>");
document.write("            </td>");
document.write("          </tr>");
document.write("        </table></td>");
document.write("      </tr>");
document.write("    </table></td>");
document.write("    <td width=\"515\" valign=\"middle\" background=\"/images/1.gif\"> <div align=\"right\"><span class=\"zuo\"><a href='/'>返回主页</a>‖<a href='http://www.95087.cn/'>电话投注</a>‖<a href='http://www.sdcp.cn/html/sjtzbf.htm'>移动手机投注</a>‖<a href='http://www.sdcp.cn/html/sjtzbf.htm'>联通手机投注</a>‖<a href='/lottery/'>网上投注</a></span>&nbsp;<br>");
document.write("    </div></td>");
document.write("  </tr>");
//document.write("  <tr>");
//document.write("    <td colspan='2'><object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0' width='777' height='94'>");
//document.write("      <param name='movie' value='../images/ad.swf'>");
//document.write("      <param name='quality' value='high'>");
//document.write("      <embed src='../images/ad.swf' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' type='application/x-shockwave-flash' width='777' height='94'></embed>");
//document.write("    </object></td>");
//document.write("  </tr>");
document.write("  <tr>");
document.write("    <td><a href='/html/cpbs/cpbs.htm'><img src=\"/images/donghua1.gif\" width=\"312\" height=\"94\" border=0></a></td>");
document.write("    <td><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0\" width=\"467\" height=\"94\">");
document.write("        <param name=\"movie\" value=\"/images/ad.swf\">");
document.write("        <param name=\"quality\" value=\"high\">");
document.write("        <embed src=\"/images/ad.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" width=\"497\" height=\"94\"></embed></object></td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td colspan=\"2\"><img src=\"/images/bannr.gif\" width=\"777\" height=\"50\" border=\"0\" usemap=\"#Map\"></td>");
document.write("  </tr>");
document.write("</table>");
document.write("<map name=\"Map\">");
document.write("  <area shape=\"rect\" coords=\"6,1,82,48\" href=\"/dncp/\">");
document.write("  <area shape=\"rect\" coords=\"94,1,168,48\" href=\"/news/tjindex.php\">");
document.write("  <area shape=\"rect\" coords=\"181,1,256,48\" href=\"/news/jkindex.php\">");
document.write("  <area shape=\"rect\" coords=\"268,1,343,48\" href=\"/news/bdindex.php\">");
document.write("  <area shape=\"rect\" coords=\"355,1,432,48\" href=\"/news/xwindex.php\">");
document.write("  <area shape=\"rect\" coords=\"438,1,517,48\" href=\"/vod/\">");
document.write("  <area shape=\"rect\" coords=\"529,1,600,48\" href=\"/news/ltindex.php\">");
document.write("  <area shape=\"rect\" coords=\"615,1,691,48\" href=\"/news/zjindex.php\">");
document.write("  <area shape=\"rect\" coords=\"703,1,773,48\" href=\"/news/zxindex.php\">");
document.write("</map>");